.TH HUCKLE 1 "FEBRUARY 2017" Linux "User Manuals"
.SH NAME
huckle \- A generic hypertext command line interface (HCLI) client
.SH SYNOPSIS
.B huckle
[
.I option
|
.I <command>
.I <parameter>
]
.SH DESCRIPTION
.B huckle
is a generic CLI that can be used with any API that abides by
the standard version 1.0 hypertext command line interface (HCLI) semantics.

A terminal restart is required after the creation of the very first CLI alias. CLI aliases created thereafter are immediately usable.

.SH COMMANDS
.IP "install <url>"
This attempts to auto configure a CLI if provided with the root URL of an HCLI API. If successful, the CLI
can be invoked by name, and its configuration is located under ~/.huckle/etc/<cliname>/config.

Note that an existing configuration file is left alone if the command is run multiple times
for the same CLI.
.IP "cli <cliname>"
Used to invoke a CLI by name, the details of which are otherwise left to API implementers.
.IP "<cliname> ..."
The <cliname> alias created for brevity, via huckle install.
.IP "<cliname> ... help"
The "help" command can be used anywhere in a command line invocation to generate help pages from an HCLI document. This
is useful to explore what a CLI can do.
.IP help
This help file.
.SH OPTIONS
.IP --version
.B huckle
version and the version of it's dependencies.
.SH EXAMPLE
huckle install https://hcli.io/hcli-webapp/cli/jsonf?command=jsonf

huckle cli jsonf (equivalent to simply invoking "jsonf" after terminal restart)

huckle --version
