.TH HUCKLE 1 "FEBRUARY 2017" Linux "User Manuals"
.SH NAME
huckle \- A generic hypertext command line interface (HCLI) client
.SH SYNOPSIS
.B huckle
[
.I option
|
.I <command>
.I <parameter>
]
.SH DESCRIPTION
.B huckle
is a generic CLI that can be used with any API that abides by
the standard version 1.0 hypertext command line interface (HCLI) semantics.
.SH COMMANDS
.IP "pull <url>"
This attempts to auto configure a CLI via the root URL of an HCLI. If successful, the CLI
can be invoked by name, after restarting the terminal, as if created via "huckle create".
   
Note that an existing configuration file is left alone if the command is run multiple times
for the same CLI.
.IP "create <cliname>"
This allows you to crete an alias into a new HCLI API. Manual configuration of the root HCLI URL
is required under ~/.huckle/cliname/config and so is restarting the terminal (since we're using a ~/.bash_profile alias).
.IP "cli <cliname>"
Used to invoke a CLI, the details of which are left to API implementers.
.IP "<cliname> ..."
The <cliname> alias created with huckle pull or huckle create can be used for brevity.
.IP "<cliname> ... help"
The "help" command can be used anywhere in a command line invocation to generate help pages from an HCLI document. This
is useful to explore what a CLI can do.
.IP help
This help file
.SH OPTIONS
.IP --version
.B huckle
version and the version of it's dependencies.
.SH EXAMPLE
huckle pull https://hcli.io/hcli-webapp/cli/jsonf?command=jsonf

huckle create usp5

huckle cli usp5 (equivalent to simply invoking "usp5" after terminal restart)

huckle --version
